added mounts added Docker binds

diff --git a/az-drun b/az-drun
--- a/az-drun
+++ b/az-drun
@@ -7,10 +7,13 @@ set -e
 # - parameter, for example: klantnaam=test
 # - container base name, default dwh-etl
 
+. ${0%/*}/urlencode.sh
+
 # use parameters, or use defaults otherwise
 environment=${1:-dev}
 param1="$2"
 param1_value="${param1#*=}"
+param1_first3="${param1_value:0:3}"
 container_base_name=${3:-dwh-etl}
 
 if [ -z "${USER}" ]
@@ -36,6 +39,73 @@ if [ "$environment" == "local" ]
 then
 	run_local=1
 fi
+
+function parse_connection_string {
+	OLD_IFS=${IFS}
+	IFS=';'
+	echo "$1" | read -s DefaultEndpointsProtocol EndpointSuffix AccountName AccountKey
+	if [ -z "${DefaultEndpointsProtocol}" ]
+	then
+		echo "error reading connection string" >&2
+		return
+	fi
+	# just eval the strings with assignments, prefix with CONN_
+	eval "CONN_${DefaultEndpointsProtocol}"
+	eval "CONN_${EndpointSuffix}"
+	eval "CONN_${AccountName}"
+	eval "CONN_${AccountKey}"
+	IFS=${OLD_IFS}
+}
+
+function do_mount {
+	arch=$(uname -s)
+	case "${arch}" in
+	Darwin)
+		open -g "$2"
+		echo "-v /Volumes/$1:/$1"
+		echo "mounted /$1" >&2
+		;;
+	*)
+		echo "mount on this platform is not supported yet" >&2
+		;;
+	esac
+}
+
+function docker_mount_binds {
+	mkdir -p mnt
+	OLD_IFS=${IFS}
+	IFS=$'\n'
+	account_ids=($(az storage account list | jq -r '.[].id'))
+	IFS=${OLD_IFS}
+	binds=()
+	for id in ${account_ids[@]}
+	do
+		connection=$(az storage account show-connection-string --ids "${id}" | jq -r ".connectionString")
+		parse_connection_string "${connection}"
+		case "${CONN_AccountName}" in
+		# if the account name equals the resource group without dashes plus 'external', we have the external storage account at hand
+		"${RESOURCE_GROUP//-/}external")
+			# get the specific key vault
+			vault_name=$(az keyvault list | jq -r ".[].name" | grep -i "${RESOURCE_GROUP}-${param1_first3}")
+			sas_token=$(az keyvault secret show --vault-name "${vault_name}" --name "sas-token" -o json | jq -r ".value")
+			key=$(rawurlencode "${CONN_AccountKey}")
+			# mount the external storage account on the param1 value
+			local_mount=$(do_mount "${param1_value}" "smb://${CONN_AccountName}:${key}@${CONN_AccountName}.file.${CONN_EndpointSuffix}/${param1_value}")
+			binds+=($local_mount)
+			;;
+		# if the account name equals the resource group without dashes, we have the default storage account at hand
+		"${RESOURCE_GROUP//-/}")
+			key=$(rawurlencode "${CONN_AccountKey}")
+			# mount the standard /data and /archive directories
+			local_mount=$(do_mount "data" "smb://${CONN_AccountName}:${key}@${CONN_AccountName}.file.${CONN_EndpointSuffix}/data")
+			binds+=($local_mount)
+			local_mount=$(do_mount "archive" "smb://${CONN_AccountName}:${key}@${CONN_AccountName}.file.${CONN_EndpointSuffix}/archive")
+			binds+=($local_mount)
+			;;
+		esac
+	done
+	echo "${binds[@]}"
+}
 
 client_name=${KEY_VAULT_NAME%-*}
 #container_name="${client_name}-${container_base_name}"
@@ -66,8 +136,9 @@ az acr login --name ${ACR_NAME} --subscription ${SUBSCRIPTION_ID}
 
 if [ ${run_local} -eq 1 ]
 then
+	binds=$(docker_mount_binds)
 	# the env vars are set again in this local run to make copy-paste of the command complete and therefore easier
-	docker run -it --rm --name "${container_name}" -e CONF_KEYVAULT="${KEY_VAULT_URI}" -e AZURE_TENANT_ID -e AZURE_CLIENT_ID="${APP_ETL_CLIENTID}" -e AZURE_CLIENT_SECRET="${APP_ETL_PASSWORD}" ${ACR_REGISTRY}/${image_name} "${container_command}"
+	docker run -it --rm "${binds}" --name "${container_name}" -e CONF_KEYVAULT="${KEY_VAULT_URI}" -e AZURE_TENANT_ID -e AZURE_CLIENT_ID="${APP_ETL_CLIENTID}" -e AZURE_CLIENT_SECRET="${APP_ETL_PASSWORD}" ${ACR_REGISTRY}/${image_name} "${container_command}"
 else
 	docker push ${ACR_REGISTRY}/${image_name}
 	# test existence of deployment group
